# Generated by Django 4.2.4 on 2023-08-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("che_project_app", "0003_car_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="fuel",
            field=models.FloatField(),
        ),
    ]
